DROP DATABASE IF EXISTS `donations`;
CREATE DATABASE `donations`; 
USE `donations`;

SET NAMES utf8 ;
SET character_set_client = utf8mb4 ;

CREATE TABLE Donors (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name TEXT NOT NULL,
    Address TEXT NOT NULL,
    ActiveStatus BOOLEAN DEFAULT TRUE,
    RegisteredSince TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Pledges (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DonorId INT,
    PledgeDate DATE NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (DonorId) REFERENCES Donors(Id) ON DELETE CASCADE
);

CREATE TABLE Payments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DonorId INT,
    PaymentDate DATE NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (DonorId) REFERENCES Donors(Id) ON DELETE CASCADE
);

CREATE TABLE PledgePayment (
    PledgeId INT,
    PaymentId INT,
    PRIMARY KEY (PledgeId, PaymentId),
    FOREIGN KEY (PaymentId) REFERENCES Payments(Id) ON DELETE CASCADE,
    FOREIGN KEY (PledgeId) REFERENCES Pledges(Id) ON DELETE CASCADE
);

CREATE TABLE Changelog (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TableName VARCHAR(100) NOT NULL,
    RecordID INT NOT NULL,
    ChangeType ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    ChangedBy VARCHAR(100),
    ChangeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ChangeDescription TEXT
);
